[EMULATED_UPS]
driver = blazer_ser
port = /dev/ttyUSB0
desc = "Emulated UPS"
default.battery.voltage.high = 13.1
default.battery.voltage.low = 11.80
default.battery.voltage.nominal = 12.25
runtimecal = 1500,100,3000,50
#offdelay values in seconds
offdelay = 60
#ondelay values in minutes
ondelay = 1

